name: ğŸš€ Deploy website

on:
  push:
    branches:
      - main

jobs:
  cpanel-cicd:
    name: ğŸ‰ Deploy

    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ›µ Go to frontend folder
        uses: cd frontend

      - name: ğŸ˜ Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: ğŸ’ I prefer yarn
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install

      - name: ğŸ› ï¸ Building
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: generate

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./.output/public/
          server-dir: ./
